version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: prod_postgres
    restart: always
    env_file: .env.prod
    ports:
      - "5433:5432"
    volumes:
      - pg_data_prod:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: prod_minio
    restart: always
    env_file: .env.prod
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data_prod:/data

  etl:
    build: ./etl
    container_name: prod_etl
    restart: "no"
    depends_on:
      - postgres
      - minio
    env_file: .env.prod
    volumes:
      - ./etl:/app
    command: python main.py

  airflow_postgres:
    image: postgres:16
    container_name: prod_airflow_db
    restart: always
    env_file: .env.prod
    ports:
      - "5434:5432"
    volumes:
      - airflow_db_prod:/var/lib/postgresql/data

  airflow_webserver:
    build: ./airflow
    container_name: prod_airflow_webserver
    restart: always
    depends_on:
      - airflow_postgres
    env_file: .env.prod
    ports:
      - "8080:8080"
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: webserver

  airflow_scheduler:
    build: ./airflow
    container_name: prod_airflow_scheduler
    restart: always
    depends_on:
      - airflow_postgres
    env_file: .env.prod
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/plugins:/opt/airflow/plugins
    command: scheduler

volumes:
  pg_data_prod:
  minio_data_prod:
  airflow_db_prod:
